version: "3.9"
services:
    database:
        image: mysql
        restart: always
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task-list
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 8080:8080
